    CharToString
    CharArrayToString
    ColorToARGB
    ColorToString
    DoubleToString
    EnumToString
    IntegerToString
    ShortToString
    ShortArrayToString
    TimeToString
    NormalizeDouble
    StringToCharArray
    StringToColor
    StringToDouble
    StringToInteger
    StringToShortArray
    StringToTime
    StringFormat
