    SymbolsTotal
    SymbolName
    SymbolSelect
    SymbolIsSynchronized
    SymbolInfoDouble
    SymbolInfoInteger
    SymbolInfoString
    SymbolInfoTick
    SymbolInfoSessionQuote
    SymbolInfoSessionTrade
    MarketBookAdd
    MarketBookRelease
    MarketBookGet
