    ObjectCreate
    ObjectName
    ObjectDelete
    ObjectsDeleteAll
    ObjectFind
    ObjectGetTimeByValue
    ObjectGetValueByTime
    ObjectMove
    ObjectsTotal
    ObjectSetDouble
    ObjectSetInteger
    ObjectSetString
    ObjectGetDouble
    ObjectGetInteger
    ObjectGetString
    TextSetFont
    TextOut
    TextGetSize
