    CLHandleType
    CLGetInfoInteger
    CLGetInfoString
    CLContextCreate
    CLContextFree
    CLGetDeviceInfo
    CLProgramCreate
    CLProgramFree
    CLKernelCreate
    CLKernelFree
    CLSetKernelArg
    CLSetKernelArgMem
    CLBufferCreate
    CLBufferFree
    CLBufferWrite
    CLBufferRead
    CLExecute
